// Generated by CoffeeScript 1.10.0

/*
*
* pot.plan.coffee
*
* PotApp
*
* Created by Julian Kleine on 26. Jan 2016
* Copyright Potschamperl 2016. All rights reserved.
*
 */
var Pot;

Pot = Pot || {};

Pot.Plan = (function() {
  function Plan(data, maxDays) {
    var i, len, ref, worker;
    this.data = data;
    this.maxDays = maxDays != null ? maxDays : 31;
    this.days = this.data.days;
    this.month = this.data.month;
    this.worker = this.data.worker;
    ref = this.worker;
    for (i = 0, len = ref.length; i < len; i++) {
      worker = ref[i];
      worker = new Pot.Worker(worker.id, worker.name, worker.role);
    }
  }

  Plan.prototype.getDay = function() {
    return this.day;
  };

  Plan.prototype.setDay = function(day) {
    return this.day = day;
  };

  return Plan;

})();
