// Generated by CoffeeScript 1.10.0

/*
*
* pot.worker.coffee
*
* PotApp
*
* Created by Julian Kleine on 26. Jan 2016
* Copyright Potschamperl 2016. All rights reserved.
*
 */
var Koch, Pot,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Pot = Pot || {};

Pot.Worker = (function() {
  function Worker(id, name, role, text1, min1, max1) {
    this.id = id;
    this.name = name;
    this.role = role;
    this.text = text1 != null ? text1 : "";
    this.min = min1 != null ? min1 : 0;
    this.max = max1 != null ? max1 : 0;
  }

  Worker.prototype.getName = function() {
    return this.name;
  };

  Worker.prototype.setAttr = function(text, min, max) {
    this.text = text;
    this.min = min;
    this.max = max;
  };

  return Worker;

})();

Koch = (function(superClass) {
  extend(Koch, superClass);

  function Koch(meals) {
    this.meals = meals;
  }

  Koch.prototype.getName = function() {
    return this.name;
  };

  return Koch;

})(Worker);
